apiVersion: v1
kind: Service
metadata:
  name: target-postgres
  namespace: airflow
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: target-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-postgres
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-postgres
  template:
    metadata:
      labels:
        app: target-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "analytics_db"
            - name: POSTGRES_USER
              value: "analytics_user"
            - name: POSTGRES_PASSWORD
              value: "analytics_password"
          ports:
            - containerPort: 5432
